name: Check SG Hyrox Page for Categories (Selenium)

on:
  schedule:
    # Runs at 08:00 UTC every day. Customize at https://crontab.guru/
    # - cron: '0 8 * * *'
    # 9am Kuala Lumpur time is 02:00 UTC in summer, 01:00 UTC in winter
    # Adjust the cron expression as needed for your timezone
    - cron: "0 0 * * *"
    - cron: "0 4 * * *"
    - cron: "0 8 * * *"
    - cron: "0 12 * * *"
    
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  check_for_updates:
    runs-on: ubuntu-latest
    # Grant write permissions to the job for committing the status file
    permissions:
      contents: write
    outputs:
      change_detected: ${{ steps.run_script.outputs.change_detected }}
      notification_body: ${{ steps.run_script.outputs.notification_body }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ---- NEW STEP: Install Google Chrome ----
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Python dependencies
        run: pip install selenium

      - name: Run Python Selenium script
        id: run_script
        run: python sg_hyrox_checker.py # Use the new script name

      - name: Commit and push status file
        if: steps.run_script.outputs.change_detected == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ${{ env.STATUS_FILE }}
          git commit -m "Update keyword status"
          git push
        env:
          STATUS_FILE: check_status.json

  send_notification:
    needs: check_for_updates
    if: needs.check_for_updates.outputs.change_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'SG Hyrox Update: New Category Available!'
          to: happychildhood@yahoo.com # <-- IMPORTANT: Change this
          from: SG Hyrox Monitor Bot happychildhood@yahoo.com # <-- IMPORTANT: Change this
          body: ${{ needs.check_for_updates.outputs.notification_body }}
