name: Check Hyrox Pages (Selenium)

on:
  schedule:
    - cron: '0 0,2,4,6,8,10,12 * * *'
  workflow_dispatch:

jobs:
  check_for_updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      changes_detected: ${{ steps.run_script.outputs.changes_detected }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Install Python dependencies
        run: pip install selenium
      - name: Run Python Selenium script
        id: run_script
        # Pass secrets to the Python script as environment variables
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: python hyrox_checker.py # Use the new script name

      # This step now commits any and all updated .json status files
      - name: Commit and push status files
        if: steps.run_script.outputs.changes_detected == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.json
          git commit -m "Update page status"
          git push
